package igu;

import entidades.Garante;
import entidades.Inquilino;
import entidades.Inspector;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.util.ArrayList;
import javax.swing.DefaultListCellRenderer;
import javax.swing.JComponent;
import javax.swing.JList;
import javax.swing.JOptionPane;
import persistencia.GaranteData;
import persistencia.InquilinoData;
import persistencia.InspectorData;

public class MenuListados extends javax.swing.JInternalFrame {

    InquilinoData inquilinoD = new InquilinoData();
    InspectorData inspectorD = new InspectorData();
    GaranteData garanteD = new GaranteData();

    public MenuListados() {
        initComponents();
        QuitarLaBarraTitulo();
        cargarCombos();
        borrarCampos();

    }
    //defino dos métodosdentro del JInternalFrame y lo instanciamos de la siguiente manera.

    private JComponent Barra = ((javax.swing.plaf.basic.BasicInternalFrameUI) getUI()).getNorthPane();
    private Dimension DimensionBarra = null;

    //A continuación creamos una función dentro del mismo JInternalFrame como el ejemplo siguiente:
    public void QuitarLaBarraTitulo() {
        Barra = ((javax.swing.plaf.basic.BasicInternalFrameUI) getUI()).getNorthPane();
        DimensionBarra = Barra.getPreferredSize();
        Barra.setSize(0, 0);
        Barra.setPreferredSize(new Dimension(0, 0));
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPCardListados = new javax.swing.JPanel();
        jPBarraNavegador3 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPInquilinos = new javax.swing.JPanel();
        jLTituloInquilinos = new javax.swing.JLabel();
        jLBusquedaInquilinos = new javax.swing.JLabel();
        jCBusquedaInquilinos = new javax.swing.JComboBox<>();
        jLIdInquilinos = new javax.swing.JLabel();
        jTIDInquilino = new javax.swing.JTextField();
        jBNuevoInquilinos = new javax.swing.JButton();
        jBModificarInquilinos = new javax.swing.JButton();
        jBEliminarInquilinos = new javax.swing.JButton();
        jBSalirInquilinos = new javax.swing.JButton();
        jTNombreInquilinos = new javax.swing.JTextField();
        jLNombreInquilinos = new javax.swing.JLabel();
        jLApellidoInquilinos = new javax.swing.JLabel();
        jTApellidoInquilinos = new javax.swing.JTextField();
        jLDNIInquilinos = new javax.swing.JLabel();
        jTDNIInquilinos = new javax.swing.JTextField();
        jLCuitInquilinos = new javax.swing.JLabel();
        jTLugarTrabajoInquilinos = new javax.swing.JTextField();
        jLLugarTrabajoInquilinos = new javax.swing.JLabel();
        jTCuitInquilinos = new javax.swing.JTextField();
        jLActivoInquilinos = new javax.swing.JLabel();
        jRInquilino = new javax.swing.JRadioButton();
        jPGarante = new javax.swing.JPanel();
        jLTituloGarante = new javax.swing.JLabel();
        jLBusquedaGarante = new javax.swing.JLabel();
        jCBusquedaGarante = new javax.swing.JComboBox<>();
        jBNuevoGarante = new javax.swing.JButton();
        jBModificarGarante = new javax.swing.JButton();
        jBEliminarGarante = new javax.swing.JButton();
        jBSalirGarante = new javax.swing.JButton();
        jLIDGarante = new javax.swing.JLabel();
        jTIDGarante = new javax.swing.JTextField();
        jLNombreGarante = new javax.swing.JLabel();
        jTNombreGarante = new javax.swing.JTextField();
        jLApellidoGarante = new javax.swing.JLabel();
        jTApellidoGarante = new javax.swing.JTextField();
        jLDNIGarante = new javax.swing.JLabel();
        jTDNIGarante = new javax.swing.JTextField();
        jLDomicilio = new javax.swing.JLabel();
        jTDomicilioGarante = new javax.swing.JTextField();
        jLTelefonoGarante = new javax.swing.JLabel();
        jTTelefonoGarante = new javax.swing.JTextField();
        jLActivoGarante = new javax.swing.JLabel();
        jRGarante = new javax.swing.JRadioButton();
        jPInspector = new javax.swing.JPanel();
        jLTituloInspector = new javax.swing.JLabel();
        jLBusquedaInspector = new javax.swing.JLabel();
        jCBusquedaInspector = new javax.swing.JComboBox<>();
        jBNuevoInspector = new javax.swing.JButton();
        jBModificarInspector = new javax.swing.JButton();
        jBEliminarInspector = new javax.swing.JButton();
        jBSalirInspector = new javax.swing.JButton();
        jLIDInspector = new javax.swing.JLabel();
        jTIDInspector = new javax.swing.JTextField();
        jLMatriculaInspector = new javax.swing.JLabel();
        jTMatriculaInspector = new javax.swing.JTextField();
        jLNombreInspector = new javax.swing.JLabel();
        jTNombreInspector = new javax.swing.JTextField();
        jLApellidoInspector = new javax.swing.JLabel();
        jTApellidoInspector = new javax.swing.JTextField();
        jLTelefonoInspector = new javax.swing.JLabel();
        jTTelefonoInspector = new javax.swing.JTextField();
        jLActivoInspector = new javax.swing.JLabel();
        jRInspector = new javax.swing.JRadioButton();

        setBorder(null);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);

        jPCardListados.setBackground(new java.awt.Color(55, 55, 55));
        jPCardListados.setMinimumSize(new java.awt.Dimension(748, 635));

        jPBarraNavegador3.setBackground(new java.awt.Color(153, 153, 153));

        jLabel29.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel29.setText("Inicio > Listados");
        jLabel29.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout jPBarraNavegador3Layout = new javax.swing.GroupLayout(jPBarraNavegador3);
        jPBarraNavegador3.setLayout(jPBarraNavegador3Layout);
        jPBarraNavegador3Layout.setHorizontalGroup(
            jPBarraNavegador3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPBarraNavegador3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(467, Short.MAX_VALUE))
        );
        jPBarraNavegador3Layout.setVerticalGroup(
            jPBarraNavegador3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPBarraNavegador3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel29)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        jPInquilinos.setBackground(new java.awt.Color(51, 51, 51));

        jLTituloInquilinos.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLTituloInquilinos.setForeground(new java.awt.Color(51, 204, 255));
        jLTituloInquilinos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLTituloInquilinos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/casita.png"))); // NOI18N
        jLTituloInquilinos.setText("  Formulario Inquilinos");
        jLTituloInquilinos.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jLBusquedaInquilinos.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLBusquedaInquilinos.setForeground(new java.awt.Color(51, 204, 255));
        jLBusquedaInquilinos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLBusquedaInquilinos.setText("Busqueda");

        jCBusquedaInquilinos.setBackground(new java.awt.Color(153, 153, 153));
        jCBusquedaInquilinos.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        jCBusquedaInquilinos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBusquedaInquilinosActionPerformed(evt);
            }
        });

        jLIdInquilinos.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLIdInquilinos.setForeground(new java.awt.Color(51, 204, 255));
        jLIdInquilinos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLIdInquilinos.setText("ID Inquilino");
        jLIdInquilinos.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jTIDInquilino.setBackground(new java.awt.Color(153, 153, 153));
        jTIDInquilino.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        jTIDInquilino.setForeground(new java.awt.Color(51, 51, 51));
        jTIDInquilino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTIDInquilinoActionPerformed(evt);
            }
        });

        jBNuevoInquilinos.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        jBNuevoInquilinos.setForeground(new java.awt.Color(51, 204, 255));
        jBNuevoInquilinos.setText("Nuevo");
        jBNuevoInquilinos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBNuevoInquilinos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBNuevoInquilinosActionPerformed(evt);
            }
        });

        jBModificarInquilinos.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        jBModificarInquilinos.setForeground(new java.awt.Color(51, 204, 255));
        jBModificarInquilinos.setText("Modificar");
        jBModificarInquilinos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBModificarInquilinos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBModificarInquilinosActionPerformed(evt);
            }
        });

        jBEliminarInquilinos.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        jBEliminarInquilinos.setForeground(new java.awt.Color(51, 204, 255));
        jBEliminarInquilinos.setText("Eliminar");
        jBEliminarInquilinos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBEliminarInquilinos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEliminarInquilinosActionPerformed(evt);
            }
        });

        jBSalirInquilinos.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        jBSalirInquilinos.setForeground(new java.awt.Color(51, 204, 255));
        jBSalirInquilinos.setText("Salir");
        jBSalirInquilinos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBSalirInquilinos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalirInquilinosActionPerformed(evt);
            }
        });

        jTNombreInquilinos.setBackground(new java.awt.Color(153, 153, 153));
        jTNombreInquilinos.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        jTNombreInquilinos.setForeground(new java.awt.Color(51, 51, 51));
        jTNombreInquilinos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTNombreInquilinosActionPerformed(evt);
            }
        });

        jLNombreInquilinos.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLNombreInquilinos.setForeground(new java.awt.Color(51, 204, 255));
        jLNombreInquilinos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLNombreInquilinos.setText("Nombre");
        jLNombreInquilinos.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jLApellidoInquilinos.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLApellidoInquilinos.setForeground(new java.awt.Color(51, 204, 255));
        jLApellidoInquilinos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLApellidoInquilinos.setText("Apellido");
        jLApellidoInquilinos.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jTApellidoInquilinos.setBackground(new java.awt.Color(153, 153, 153));
        jTApellidoInquilinos.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        jTApellidoInquilinos.setForeground(new java.awt.Color(51, 51, 51));
        jTApellidoInquilinos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTApellidoInquilinosActionPerformed(evt);
            }
        });

        jLDNIInquilinos.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLDNIInquilinos.setForeground(new java.awt.Color(51, 204, 255));
        jLDNIInquilinos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLDNIInquilinos.setText("DNI");
        jLDNIInquilinos.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jTDNIInquilinos.setBackground(new java.awt.Color(153, 153, 153));
        jTDNIInquilinos.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        jTDNIInquilinos.setForeground(new java.awt.Color(51, 51, 51));
        jTDNIInquilinos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTDNIInquilinosActionPerformed(evt);
            }
        });

        jLCuitInquilinos.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLCuitInquilinos.setForeground(new java.awt.Color(51, 204, 255));
        jLCuitInquilinos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLCuitInquilinos.setText("CUIT");
        jLCuitInquilinos.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jTLugarTrabajoInquilinos.setBackground(new java.awt.Color(153, 153, 153));
        jTLugarTrabajoInquilinos.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        jTLugarTrabajoInquilinos.setForeground(new java.awt.Color(51, 51, 51));
        jTLugarTrabajoInquilinos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTLugarTrabajoInquilinosActionPerformed(evt);
            }
        });

        jLLugarTrabajoInquilinos.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLLugarTrabajoInquilinos.setForeground(new java.awt.Color(51, 204, 255));
        jLLugarTrabajoInquilinos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLLugarTrabajoInquilinos.setText("Lugar de Trabajo");
        jLLugarTrabajoInquilinos.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jTCuitInquilinos.setBackground(new java.awt.Color(153, 153, 153));
        jTCuitInquilinos.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        jTCuitInquilinos.setForeground(new java.awt.Color(51, 51, 51));
        jTCuitInquilinos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTCuitInquilinosActionPerformed(evt);
            }
        });

        jLActivoInquilinos.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLActivoInquilinos.setForeground(new java.awt.Color(51, 204, 255));
        jLActivoInquilinos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLActivoInquilinos.setText("Activo");
        jLActivoInquilinos.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jRInquilino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRInquilinoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPInquilinosLayout = new javax.swing.GroupLayout(jPInquilinos);
        jPInquilinos.setLayout(jPInquilinosLayout);
        jPInquilinosLayout.setHorizontalGroup(
            jPInquilinosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPInquilinosLayout.createSequentialGroup()
                .addContainerGap(248, Short.MAX_VALUE)
                .addComponent(jLTituloInquilinos)
                .addGap(242, 242, 242))
            .addGroup(jPInquilinosLayout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addGroup(jPInquilinosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPInquilinosLayout.createSequentialGroup()
                        .addComponent(jBNuevoInquilinos)
                        .addGap(18, 18, 18)
                        .addComponent(jBModificarInquilinos)
                        .addGap(18, 18, 18)
                        .addComponent(jBEliminarInquilinos)
                        .addGap(18, 18, 18)
                        .addComponent(jBSalirInquilinos))
                    .addGroup(jPInquilinosLayout.createSequentialGroup()
                        .addComponent(jLBusquedaInquilinos)
                        .addGap(18, 18, 18)
                        .addComponent(jCBusquedaInquilinos, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPInquilinosLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPInquilinosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPInquilinosLayout.createSequentialGroup()
                                .addComponent(jLIdInquilinos, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTIDInquilino, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPInquilinosLayout.createSequentialGroup()
                                .addComponent(jLApellidoInquilinos, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTApellidoInquilinos, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPInquilinosLayout.createSequentialGroup()
                                .addComponent(jLDNIInquilinos, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTDNIInquilinos, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPInquilinosLayout.createSequentialGroup()
                                .addComponent(jLNombreInquilinos, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTNombreInquilinos, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPInquilinosLayout.createSequentialGroup()
                                .addComponent(jLCuitInquilinos, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTCuitInquilinos, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPInquilinosLayout.createSequentialGroup()
                                .addGroup(jPInquilinosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLLugarTrabajoInquilinos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLActivoInquilinos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPInquilinosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRInquilino)
                                    .addComponent(jTLugarTrabajoInquilinos, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(0, 210, Short.MAX_VALUE))
        );
        jPInquilinosLayout.setVerticalGroup(
            jPInquilinosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPInquilinosLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLTituloInquilinos)
                .addGap(31, 31, 31)
                .addGroup(jPInquilinosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLBusquedaInquilinos)
                    .addComponent(jCBusquedaInquilinos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(jPInquilinosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTIDInquilino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLIdInquilinos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPInquilinosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTNombreInquilinos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLNombreInquilinos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPInquilinosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTApellidoInquilinos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLApellidoInquilinos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPInquilinosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTDNIInquilinos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLDNIInquilinos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPInquilinosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTCuitInquilinos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLCuitInquilinos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPInquilinosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTLugarTrabajoInquilinos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLLugarTrabajoInquilinos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPInquilinosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLActivoInquilinos)
                    .addComponent(jRInquilino))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addGroup(jPInquilinosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBSalirInquilinos)
                    .addComponent(jBNuevoInquilinos)
                    .addComponent(jBModificarInquilinos)
                    .addComponent(jBEliminarInquilinos))
                .addGap(65, 65, 65))
        );

        jTabbedPane1.addTab("INQUILINOS", jPInquilinos);

        jPGarante.setBackground(new java.awt.Color(51, 51, 51));

        jLTituloGarante.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLTituloGarante.setForeground(new java.awt.Color(51, 204, 255));
        jLTituloGarante.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLTituloGarante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/casita.png"))); // NOI18N
        jLTituloGarante.setText("  Formulario Garante");
        jLTituloGarante.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jLBusquedaGarante.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLBusquedaGarante.setForeground(new java.awt.Color(51, 204, 255));
        jLBusquedaGarante.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLBusquedaGarante.setText("Busqueda");
        jLBusquedaGarante.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jCBusquedaGarante.setBackground(new java.awt.Color(153, 153, 153));
        jCBusquedaGarante.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        jCBusquedaGarante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBusquedaGaranteActionPerformed(evt);
            }
        });

        jBNuevoGarante.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        jBNuevoGarante.setForeground(new java.awt.Color(51, 204, 255));
        jBNuevoGarante.setText("Nuevo");
        jBNuevoGarante.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBNuevoGarante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBNuevoGaranteActionPerformed(evt);
            }
        });

        jBModificarGarante.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        jBModificarGarante.setForeground(new java.awt.Color(51, 204, 255));
        jBModificarGarante.setText("Modificar");
        jBModificarGarante.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBModificarGarante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBModificarGaranteActionPerformed(evt);
            }
        });

        jBEliminarGarante.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        jBEliminarGarante.setForeground(new java.awt.Color(51, 204, 255));
        jBEliminarGarante.setText("Eliminar");
        jBEliminarGarante.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBEliminarGarante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEliminarGaranteActionPerformed(evt);
            }
        });

        jBSalirGarante.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        jBSalirGarante.setForeground(new java.awt.Color(51, 204, 255));
        jBSalirGarante.setText("Salir");
        jBSalirGarante.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBSalirGarante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalirGaranteActionPerformed(evt);
            }
        });

        jLIDGarante.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLIDGarante.setForeground(new java.awt.Color(51, 204, 255));
        jLIDGarante.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLIDGarante.setText("ID Garante");
        jLIDGarante.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jTIDGarante.setBackground(new java.awt.Color(153, 153, 153));
        jTIDGarante.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        jTIDGarante.setForeground(new java.awt.Color(51, 51, 51));
        jTIDGarante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTIDGaranteActionPerformed(evt);
            }
        });

        jLNombreGarante.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLNombreGarante.setForeground(new java.awt.Color(51, 204, 255));
        jLNombreGarante.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLNombreGarante.setText("Nombre");
        jLNombreGarante.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jTNombreGarante.setBackground(new java.awt.Color(153, 153, 153));
        jTNombreGarante.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        jTNombreGarante.setForeground(new java.awt.Color(51, 51, 51));
        jTNombreGarante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTNombreGaranteActionPerformed(evt);
            }
        });

        jLApellidoGarante.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLApellidoGarante.setForeground(new java.awt.Color(51, 204, 255));
        jLApellidoGarante.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLApellidoGarante.setText("Apellido");
        jLApellidoGarante.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jTApellidoGarante.setBackground(new java.awt.Color(153, 153, 153));
        jTApellidoGarante.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        jTApellidoGarante.setForeground(new java.awt.Color(51, 51, 51));
        jTApellidoGarante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTApellidoGaranteActionPerformed(evt);
            }
        });

        jLDNIGarante.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLDNIGarante.setForeground(new java.awt.Color(51, 204, 255));
        jLDNIGarante.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLDNIGarante.setText("DNI");
        jLDNIGarante.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jTDNIGarante.setBackground(new java.awt.Color(153, 153, 153));
        jTDNIGarante.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        jTDNIGarante.setForeground(new java.awt.Color(51, 51, 51));
        jTDNIGarante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTDNIGaranteActionPerformed(evt);
            }
        });

        jLDomicilio.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLDomicilio.setForeground(new java.awt.Color(51, 204, 255));
        jLDomicilio.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLDomicilio.setText("Domicilio");
        jLDomicilio.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jTDomicilioGarante.setBackground(new java.awt.Color(153, 153, 153));
        jTDomicilioGarante.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        jTDomicilioGarante.setForeground(new java.awt.Color(51, 51, 51));
        jTDomicilioGarante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTDomicilioGaranteActionPerformed(evt);
            }
        });

        jLTelefonoGarante.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLTelefonoGarante.setForeground(new java.awt.Color(51, 204, 255));
        jLTelefonoGarante.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLTelefonoGarante.setText("Telefono");
        jLTelefonoGarante.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jTTelefonoGarante.setBackground(new java.awt.Color(153, 153, 153));
        jTTelefonoGarante.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        jTTelefonoGarante.setForeground(new java.awt.Color(51, 51, 51));
        jTTelefonoGarante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTTelefonoGaranteActionPerformed(evt);
            }
        });

        jLActivoGarante.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLActivoGarante.setForeground(new java.awt.Color(51, 204, 255));
        jLActivoGarante.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLActivoGarante.setText("Activo");
        jLActivoGarante.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jRGarante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRGaranteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPGaranteLayout = new javax.swing.GroupLayout(jPGarante);
        jPGarante.setLayout(jPGaranteLayout);
        jPGaranteLayout.setHorizontalGroup(
            jPGaranteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPGaranteLayout.createSequentialGroup()
                .addGroup(jPGaranteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPGaranteLayout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(jLTituloGarante))
                    .addGroup(jPGaranteLayout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(jLBusquedaGarante)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCBusquedaGarante, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(249, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPGaranteLayout.createSequentialGroup()
                .addGap(0, 235, Short.MAX_VALUE)
                .addGroup(jPGaranteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPGaranteLayout.createSequentialGroup()
                        .addComponent(jBNuevoGarante)
                        .addGap(18, 18, 18)
                        .addComponent(jBModificarGarante)
                        .addGap(18, 18, 18)
                        .addComponent(jBEliminarGarante)
                        .addGap(18, 18, 18)
                        .addComponent(jBSalirGarante)
                        .addGap(167, 167, 167))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPGaranteLayout.createSequentialGroup()
                        .addComponent(jRGarante)
                        .addGap(331, 331, 331))))
            .addGroup(jPGaranteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPGaranteLayout.createSequentialGroup()
                    .addGap(233, 233, 233)
                    .addGroup(jPGaranteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPGaranteLayout.createSequentialGroup()
                            .addComponent(jLIDGarante, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTIDGarante, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPGaranteLayout.createSequentialGroup()
                            .addComponent(jLApellidoGarante, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTApellidoGarante, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPGaranteLayout.createSequentialGroup()
                            .addComponent(jLDNIGarante, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTDNIGarante, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPGaranteLayout.createSequentialGroup()
                            .addComponent(jLNombreGarante, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTNombreGarante, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPGaranteLayout.createSequentialGroup()
                            .addComponent(jLDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTDomicilioGarante, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPGaranteLayout.createSequentialGroup()
                            .addComponent(jLTelefonoGarante, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTTelefonoGarante, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPGaranteLayout.createSequentialGroup()
                            .addComponent(jLActivoGarante, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(128, 128, 128)))
                    .addContainerGap(250, Short.MAX_VALUE)))
        );
        jPGaranteLayout.setVerticalGroup(
            jPGaranteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPGaranteLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLTituloGarante)
                .addGap(37, 37, 37)
                .addGroup(jPGaranteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLBusquedaGarante)
                    .addComponent(jCBusquedaGarante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 239, Short.MAX_VALUE)
                .addComponent(jRGarante)
                .addGap(80, 80, 80)
                .addGroup(jPGaranteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBNuevoGarante)
                    .addComponent(jBModificarGarante)
                    .addComponent(jBEliminarGarante)
                    .addComponent(jBSalirGarante))
                .addGap(66, 66, 66))
            .addGroup(jPGaranteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPGaranteLayout.createSequentialGroup()
                    .addGap(167, 167, 167)
                    .addGroup(jPGaranteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTIDGarante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLIDGarante))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPGaranteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTNombreGarante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLNombreGarante))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPGaranteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTApellidoGarante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLApellidoGarante))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPGaranteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTDNIGarante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLDNIGarante))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPGaranteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTDomicilioGarante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLDomicilio))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPGaranteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTTelefonoGarante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLTelefonoGarante))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLActivoGarante)
                    .addContainerGap(196, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("GARANTES", jPGarante);

        jPInspector.setBackground(new java.awt.Color(51, 51, 51));

        jLTituloInspector.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLTituloInspector.setForeground(new java.awt.Color(51, 204, 255));
        jLTituloInspector.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLTituloInspector.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/casita.png"))); // NOI18N
        jLTituloInspector.setText("  Formulario Inspector");
        jLTituloInspector.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jLBusquedaInspector.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLBusquedaInspector.setForeground(new java.awt.Color(51, 204, 255));
        jLBusquedaInspector.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLBusquedaInspector.setText("Busqueda");
        jLBusquedaInspector.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jCBusquedaInspector.setBackground(new java.awt.Color(153, 153, 153));
        jCBusquedaInspector.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        jCBusquedaInspector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBusquedaInspectorActionPerformed(evt);
            }
        });

        jBNuevoInspector.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        jBNuevoInspector.setForeground(new java.awt.Color(51, 204, 255));
        jBNuevoInspector.setText("Nuevo");
        jBNuevoInspector.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBNuevoInspector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBNuevoInspectorActionPerformed(evt);
            }
        });

        jBModificarInspector.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        jBModificarInspector.setForeground(new java.awt.Color(51, 204, 255));
        jBModificarInspector.setText("Modificar");
        jBModificarInspector.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBModificarInspector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBModificarInspectorActionPerformed(evt);
            }
        });

        jBEliminarInspector.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        jBEliminarInspector.setForeground(new java.awt.Color(51, 204, 255));
        jBEliminarInspector.setText("Eliminar");
        jBEliminarInspector.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBEliminarInspector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEliminarInspectorActionPerformed(evt);
            }
        });

        jBSalirInspector.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        jBSalirInspector.setForeground(new java.awt.Color(51, 204, 255));
        jBSalirInspector.setText("Salir");
        jBSalirInspector.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBSalirInspector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalirInspectorActionPerformed(evt);
            }
        });

        jLIDInspector.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLIDInspector.setForeground(new java.awt.Color(51, 204, 255));
        jLIDInspector.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLIDInspector.setText("ID Inspector");
        jLIDInspector.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jTIDInspector.setBackground(new java.awt.Color(153, 153, 153));
        jTIDInspector.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        jTIDInspector.setForeground(new java.awt.Color(51, 51, 51));
        jTIDInspector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTIDInspectorActionPerformed(evt);
            }
        });

        jLMatriculaInspector.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLMatriculaInspector.setForeground(new java.awt.Color(51, 204, 255));
        jLMatriculaInspector.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLMatriculaInspector.setText("Matricula");
        jLMatriculaInspector.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jTMatriculaInspector.setBackground(new java.awt.Color(153, 153, 153));
        jTMatriculaInspector.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        jTMatriculaInspector.setForeground(new java.awt.Color(51, 51, 51));
        jTMatriculaInspector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTMatriculaInspectorActionPerformed(evt);
            }
        });

        jLNombreInspector.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLNombreInspector.setForeground(new java.awt.Color(51, 204, 255));
        jLNombreInspector.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLNombreInspector.setText("Nombre");
        jLNombreInspector.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jTNombreInspector.setBackground(new java.awt.Color(153, 153, 153));
        jTNombreInspector.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        jTNombreInspector.setForeground(new java.awt.Color(51, 51, 51));
        jTNombreInspector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTNombreInspectorActionPerformed(evt);
            }
        });

        jLApellidoInspector.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLApellidoInspector.setForeground(new java.awt.Color(51, 204, 255));
        jLApellidoInspector.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLApellidoInspector.setText("Apellido");
        jLApellidoInspector.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jTApellidoInspector.setBackground(new java.awt.Color(153, 153, 153));
        jTApellidoInspector.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        jTApellidoInspector.setForeground(new java.awt.Color(51, 51, 51));
        jTApellidoInspector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTApellidoInspectorActionPerformed(evt);
            }
        });

        jLTelefonoInspector.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLTelefonoInspector.setForeground(new java.awt.Color(51, 204, 255));
        jLTelefonoInspector.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLTelefonoInspector.setText("Telefono");
        jLTelefonoInspector.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jTTelefonoInspector.setBackground(new java.awt.Color(153, 153, 153));
        jTTelefonoInspector.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        jTTelefonoInspector.setForeground(new java.awt.Color(51, 51, 51));
        jTTelefonoInspector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTTelefonoInspectorActionPerformed(evt);
            }
        });

        jLActivoInspector.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLActivoInspector.setForeground(new java.awt.Color(51, 204, 255));
        jLActivoInspector.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLActivoInspector.setText("Activo");
        jLActivoInspector.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jRInspector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRInspectorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPInspectorLayout = new javax.swing.GroupLayout(jPInspector);
        jPInspector.setLayout(jPInspectorLayout);
        jPInspectorLayout.setHorizontalGroup(
            jPInspectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPInspectorLayout.createSequentialGroup()
                .addGroup(jPInspectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPInspectorLayout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(jLTituloInspector))
                    .addGroup(jPInspectorLayout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(jLBusquedaInspector)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCBusquedaInspector, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(241, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPInspectorLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPInspectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jRInspector)
                    .addGroup(jPInspectorLayout.createSequentialGroup()
                        .addComponent(jBNuevoInspector)
                        .addGap(18, 18, 18)
                        .addComponent(jBModificarInspector)))
                .addGap(18, 18, 18)
                .addComponent(jBEliminarInspector)
                .addGap(18, 18, 18)
                .addComponent(jBSalirInspector)
                .addGap(160, 160, 160))
            .addGroup(jPInspectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPInspectorLayout.createSequentialGroup()
                    .addGap(233, 233, 233)
                    .addGroup(jPInspectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPInspectorLayout.createSequentialGroup()
                            .addComponent(jLIDInspector, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTIDInspector, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPInspectorLayout.createSequentialGroup()
                            .addComponent(jLNombreInspector, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTNombreInspector, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPInspectorLayout.createSequentialGroup()
                            .addComponent(jLApellidoInspector, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTApellidoInspector, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPInspectorLayout.createSequentialGroup()
                            .addComponent(jLMatriculaInspector, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTMatriculaInspector, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPInspectorLayout.createSequentialGroup()
                            .addComponent(jLTelefonoInspector, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTTelefonoInspector, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPInspectorLayout.createSequentialGroup()
                            .addComponent(jLActivoInspector, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(128, 128, 128)))
                    .addContainerGap(250, Short.MAX_VALUE)))
        );
        jPInspectorLayout.setVerticalGroup(
            jPInspectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPInspectorLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLTituloInspector)
                .addGap(37, 37, 37)
                .addGroup(jPInspectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLBusquedaInspector)
                    .addComponent(jCBusquedaInspector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 226, Short.MAX_VALUE)
                .addComponent(jRInspector)
                .addGap(76, 76, 76)
                .addGroup(jPInspectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBNuevoInspector)
                    .addComponent(jBModificarInspector)
                    .addComponent(jBEliminarInspector)
                    .addComponent(jBSalirInspector))
                .addGap(83, 83, 83))
            .addGroup(jPInspectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPInspectorLayout.createSequentialGroup()
                    .addGap(182, 182, 182)
                    .addGroup(jPInspectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTIDInspector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLIDInspector))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPInspectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTMatriculaInspector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLMatriculaInspector))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPInspectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTNombreInspector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLNombreInspector))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPInspectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTApellidoInspector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLApellidoInspector))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPInspectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTTelefonoInspector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLTelefonoInspector))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLActivoInspector)
                    .addContainerGap(211, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("INSPECTORES", jPInspector);

        javax.swing.GroupLayout jPCardListadosLayout = new javax.swing.GroupLayout(jPCardListados);
        jPCardListados.setLayout(jPCardListadosLayout);
        jPCardListadosLayout.setHorizontalGroup(
            jPCardListadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPCardListadosLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPBarraNavegador3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPCardListadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        jPCardListadosLayout.setVerticalGroup(
            jPCardListadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCardListadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPBarraNavegador3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 765, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPCardListados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 658, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPCardListados, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTIDInquilinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTIDInquilinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTIDInquilinoActionPerformed

    private void jTNombreInquilinosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTNombreInquilinosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTNombreInquilinosActionPerformed

    private void jTApellidoInquilinosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTApellidoInquilinosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTApellidoInquilinosActionPerformed

    private void jTDNIInquilinosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTDNIInquilinosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTDNIInquilinosActionPerformed

    private void jTLugarTrabajoInquilinosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTLugarTrabajoInquilinosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTLugarTrabajoInquilinosActionPerformed

    private void jTCuitInquilinosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTCuitInquilinosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTCuitInquilinosActionPerformed

    private void jTIDGaranteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTIDGaranteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTIDGaranteActionPerformed

    private void jTNombreGaranteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTNombreGaranteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTNombreGaranteActionPerformed

    private void jTApellidoGaranteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTApellidoGaranteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTApellidoGaranteActionPerformed

    private void jTDNIGaranteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTDNIGaranteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTDNIGaranteActionPerformed

    private void jTDomicilioGaranteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTDomicilioGaranteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTDomicilioGaranteActionPerformed

    private void jTTelefonoGaranteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTTelefonoGaranteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTTelefonoGaranteActionPerformed

    private void jBNuevoInspectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNuevoInspectorActionPerformed
        String matricula = jTMatriculaInspector.getText();
        String nombre = jTNombreInspector.getText();
        String apellido = jTApellidoInspector.getText();
        int telefono = Integer.parseInt(jTTelefonoInspector.getText());
        boolean activo = jRInspector.isSelected();

        Inspector nuevo = new Inspector(matricula, nombre, apellido, telefono, activo);
        inspectorD.guardarInspector(nuevo);

        cargarCombos();
        borrarCampos();
    }//GEN-LAST:event_jBNuevoInspectorActionPerformed

    private void jBModificarInspectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBModificarInspectorActionPerformed
        try {

            int idInspector = Integer.parseInt(jTIDInspector.getText());
            String matricula = jTMatriculaInspector.getText();
            String nombre = jTNombreInspector.getText();
            String apellido = jTApellidoInspector.getText();
            int telefono = Integer.parseInt(jTTelefonoInspector.getText());
            boolean activo = jRInspector.isSelected();

            Inspector nuevo = new Inspector(idInspector, matricula, nombre, apellido, telefono, activo);
            inspectorD.modificarInspector(nuevo);
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(this, "Error al modificar" + e.getMessage());
        }
        cargarCombos();
        borrarCampos();

    }//GEN-LAST:event_jBModificarInspectorActionPerformed

    private void jBEliminarInspectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEliminarInspectorActionPerformed
        Inspector inspectorSeleccionado = (Inspector) jCBusquedaInspector.getSelectedItem();
        inspectorD.eliminarInspector(inspectorSeleccionado.getIdInspector());

        cargarCombos();
        borrarCampos();
        //Deshabilito botones luego de ejecutar acccion!
        //desHabilitarBotones();
    }//GEN-LAST:event_jBEliminarInspectorActionPerformed

    private void jTIDInspectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTIDInspectorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTIDInspectorActionPerformed

    private void jTMatriculaInspectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTMatriculaInspectorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTMatriculaInspectorActionPerformed

    private void jTNombreInspectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTNombreInspectorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTNombreInspectorActionPerformed

    private void jTApellidoInspectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTApellidoInspectorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTApellidoInspectorActionPerformed

    private void jTTelefonoInspectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTTelefonoInspectorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTTelefonoInspectorActionPerformed

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        int SelectPestaña = jTabbedPane1.getSelectedIndex();
        if (SelectPestaña == 0) {
            paraListadosInquilinosTrue();
        } else if (SelectPestaña == 1) {
            paraListadosGaranteTrue();
        } else if (SelectPestaña == 2) {
            paraListadosInspectorTrue();
        }
    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void jCBusquedaInquilinosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBusquedaInquilinosActionPerformed
        rellenarCampos();
    }//GEN-LAST:event_jCBusquedaInquilinosActionPerformed

    private void jCBusquedaGaranteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBusquedaGaranteActionPerformed
        rellenarCampos();
    }//GEN-LAST:event_jCBusquedaGaranteActionPerformed

    private void jCBusquedaInspectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBusquedaInspectorActionPerformed
        rellenarCampos();
    }//GEN-LAST:event_jCBusquedaInspectorActionPerformed

    private void jBNuevoInquilinosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNuevoInquilinosActionPerformed
       String nombre = jTNombreInquilinos.getText();
        String apellido = jTApellidoInquilinos.getText();
        int dni = Integer.parseInt(jTDNIInquilinos.getText());
        int cuit = Integer.parseInt(jTCuitInquilinos.getText());
        String lugarTrabajo = jTLugarTrabajoInquilinos.getText();
        boolean activo = jRInquilino.isSelected();
        Inquilino nuevo = new Inquilino(nombre, apellido, dni, cuit, lugarTrabajo, activo);
        inquilinoD.guardarInquilino(nuevo);

        cargarCombos();
        borrarCampos();
    }//GEN-LAST:event_jBNuevoInquilinosActionPerformed

    private void jBModificarInquilinosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBModificarInquilinosActionPerformed
      try {

            int idInquilino = Integer.parseInt(jTIDInquilino.getText());
            String nombre = jTNombreInquilinos.getText();
            String apellido = jTApellidoInquilinos.getText();
            int dni = Integer.parseInt(jTDNIInquilinos.getText());
            int cuit = Integer.parseInt(jTCuitInquilinos.getText());
            String lugarTrabajo = jTLugarTrabajoInquilinos.getText();
            boolean activo = jRInquilino.isSelected();

            Inquilino nuevo = new Inquilino(idInquilino, nombre, apellido, dni, cuit, lugarTrabajo, activo);
            inquilinoD.modificarInquilino(nuevo);
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(this, "Error al modificar" + e.getMessage());
        }
        cargarCombos();
        borrarCampos();
    }//GEN-LAST:event_jBModificarInquilinosActionPerformed

    private void jBEliminarInquilinosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEliminarInquilinosActionPerformed
       
        Inquilino inquilinoSelecionado = (Inquilino) jCBusquedaInquilinos.getSelectedItem();
        inquilinoD.eliminarInquilino(inquilinoSelecionado.getDni());

        cargarCombos();
        borrarCampos();
        //Deshabilito botones luego de ejecutar acccion!
        //desHabilitarBotones();
    }//GEN-LAST:event_jBEliminarInquilinosActionPerformed

    private void jBNuevoGaranteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNuevoGaranteActionPerformed
    String nombre = jTNombreGarante.getText();
        String apellido = jTApellidoGarante.getText();
        int dni = Integer.parseInt(jTDNIGarante.getText());
        String domicilio = jTDomicilioGarante.getText();
        int telefono = Integer.parseInt(jTTelefonoGarante.getText());
        boolean activo = jRGarante.isSelected();
        Garante nuevo = new Garante(nombre, apellido, dni, domicilio, telefono, activo);
        garanteD.guardarGarante(nuevo);
        cargarCombos();
        borrarCampos();
    }//GEN-LAST:event_jBNuevoGaranteActionPerformed

    private void jBModificarGaranteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBModificarGaranteActionPerformed
            try {

            int idGarante = Integer.parseInt(jTIDGarante.getText());
            String nombre = jTNombreGarante.getText();
            String apellido = jTApellidoGarante.getText();
            int dni = Integer.parseInt(jTDNIGarante.getText());
            String domicilio = jTDomicilioGarante.getText();
            int telefono = Integer.parseInt(jTTelefonoGarante.getText());
            boolean activo = jRGarante.isSelected();

            Garante nuevo = new Garante(idGarante, nombre, apellido, dni, domicilio, telefono, activo);
            garanteD.modificarGarante(nuevo);
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(this, "Error al modificar" + e.getMessage());
        }
        cargarCombos();
        borrarCampos();

    }//GEN-LAST:event_jBModificarGaranteActionPerformed

    private void jBEliminarGaranteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEliminarGaranteActionPerformed
             Garante garanteSelecionado = (Garante) jCBusquedaGarante.getSelectedItem();
        garanteD.eliminarGarante(garanteSelecionado.getDni());

        cargarCombos();
        borrarCampos();
        //Deshabilito botones luego de ejecutar acccion!
        //desHabilitarBotones();
    }//GEN-LAST:event_jBEliminarGaranteActionPerformed

    private void jBSalirGaranteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalirGaranteActionPerformed
            this.dispose();
//     jPCardFondo.setVisible(true);
    }//GEN-LAST:event_jBSalirGaranteActionPerformed

    private void jBSalirInquilinosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalirInquilinosActionPerformed
        this.dispose();
//     jPCardFondo.setVisible(true);
    }//GEN-LAST:event_jBSalirInquilinosActionPerformed

    private void jBSalirInspectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalirInspectorActionPerformed
           this.dispose();
//     jPCardFondo.setVisible(true);
    }//GEN-LAST:event_jBSalirInspectorActionPerformed

    private void jRInquilinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRInquilinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRInquilinoActionPerformed

    private void jRGaranteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRGaranteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRGaranteActionPerformed

    private void jRInspectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRInspectorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRInspectorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBEliminarGarante;
    private javax.swing.JButton jBEliminarInquilinos;
    private javax.swing.JButton jBEliminarInspector;
    private javax.swing.JButton jBModificarGarante;
    private javax.swing.JButton jBModificarInquilinos;
    private javax.swing.JButton jBModificarInspector;
    private javax.swing.JButton jBNuevoGarante;
    private javax.swing.JButton jBNuevoInquilinos;
    private javax.swing.JButton jBNuevoInspector;
    private javax.swing.JButton jBSalirGarante;
    private javax.swing.JButton jBSalirInquilinos;
    private javax.swing.JButton jBSalirInspector;
    private javax.swing.JComboBox<Garante> jCBusquedaGarante;
    private javax.swing.JComboBox<Inquilino> jCBusquedaInquilinos;
    private javax.swing.JComboBox<Inspector> jCBusquedaInspector;
    private javax.swing.JLabel jLActivoGarante;
    private javax.swing.JLabel jLActivoInquilinos;
    private javax.swing.JLabel jLActivoInspector;
    private javax.swing.JLabel jLApellidoGarante;
    private javax.swing.JLabel jLApellidoInquilinos;
    private javax.swing.JLabel jLApellidoInspector;
    private javax.swing.JLabel jLBusquedaGarante;
    private javax.swing.JLabel jLBusquedaInquilinos;
    private javax.swing.JLabel jLBusquedaInspector;
    private javax.swing.JLabel jLCuitInquilinos;
    private javax.swing.JLabel jLDNIGarante;
    private javax.swing.JLabel jLDNIInquilinos;
    private javax.swing.JLabel jLDomicilio;
    private javax.swing.JLabel jLIDGarante;
    private javax.swing.JLabel jLIDInspector;
    private javax.swing.JLabel jLIdInquilinos;
    private javax.swing.JLabel jLLugarTrabajoInquilinos;
    private javax.swing.JLabel jLMatriculaInspector;
    private javax.swing.JLabel jLNombreGarante;
    private javax.swing.JLabel jLNombreInquilinos;
    private javax.swing.JLabel jLNombreInspector;
    private javax.swing.JLabel jLTelefonoGarante;
    private javax.swing.JLabel jLTelefonoInspector;
    private javax.swing.JLabel jLTituloGarante;
    private javax.swing.JLabel jLTituloInquilinos;
    private javax.swing.JLabel jLTituloInspector;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JPanel jPBarraNavegador3;
    private javax.swing.JPanel jPCardListados;
    private javax.swing.JPanel jPGarante;
    private javax.swing.JPanel jPInquilinos;
    private javax.swing.JPanel jPInspector;
    private javax.swing.JRadioButton jRGarante;
    private javax.swing.JRadioButton jRInquilino;
    private javax.swing.JRadioButton jRInspector;
    private javax.swing.JTextField jTApellidoGarante;
    private javax.swing.JTextField jTApellidoInquilinos;
    private javax.swing.JTextField jTApellidoInspector;
    private javax.swing.JTextField jTCuitInquilinos;
    private javax.swing.JTextField jTDNIGarante;
    private javax.swing.JTextField jTDNIInquilinos;
    private javax.swing.JTextField jTDomicilioGarante;
    private javax.swing.JTextField jTIDGarante;
    private javax.swing.JTextField jTIDInquilino;
    private javax.swing.JTextField jTIDInspector;
    private javax.swing.JTextField jTLugarTrabajoInquilinos;
    private javax.swing.JTextField jTMatriculaInspector;
    private javax.swing.JTextField jTNombreGarante;
    private javax.swing.JTextField jTNombreInquilinos;
    private javax.swing.JTextField jTNombreInspector;
    private javax.swing.JTextField jTTelefonoGarante;
    private javax.swing.JTextField jTTelefonoInspector;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
 public void paraListadosInquilinos() {
        jTabbedPane1.setVisible(false);
        jPInquilinos.setVisible(false);
        jLTituloInquilinos.setVisible(false);
        jLBusquedaInquilinos.setVisible(false);
        jCBusquedaInquilinos.setVisible(false);
        jLIdInquilinos.setVisible(false);
        jTIDInquilino.setVisible(false);
        jBNuevoInquilinos.setVisible(false);
        jBModificarInquilinos.setVisible(false);
        jBEliminarInquilinos.setVisible(false);
        jBSalirInquilinos.setVisible(false);
        jTNombreInquilinos.setVisible(false);
        jLNombreInquilinos.setVisible(false);
        jLApellidoInquilinos.setVisible(false);
        jTApellidoInquilinos.setVisible(false);
        jLDNIInquilinos.setVisible(false);
        jTDNIInquilinos.setVisible(false);
        jLCuitInquilinos.setVisible(false);
        jTLugarTrabajoInquilinos.setVisible(false);
        jLLugarTrabajoInquilinos.setVisible(false);
        jTCuitInquilinos.setVisible(false);
        jLActivoInquilinos.setVisible(false);
        jRInquilino.setVisible(false);

    }

    public void paraListadosGarante() {
        jPGarante.setVisible(false);
        jLTituloGarante.setVisible(false);
        jLBusquedaGarante.setVisible(false);
        jCBusquedaGarante.setVisible(false);
        jBNuevoGarante.setVisible(false);
        jBModificarGarante.setVisible(false);
        jBEliminarGarante.setVisible(false);
        jBSalirGarante.setVisible(false);
        jLIDGarante.setVisible(false);
        jTIDGarante.setVisible(false);
        jLNombreGarante.setVisible(false);
        jTNombreGarante.setVisible(false);
        jLApellidoGarante.setVisible(false);
        jTApellidoGarante.setVisible(false);
        jLDNIGarante.setVisible(false);
        jTDNIGarante.setVisible(false);
        jLDomicilio.setVisible(false);
        jTDomicilioGarante.setVisible(false);
        jLTelefonoGarante.setVisible(false);
        jLActivoGarante.setVisible(false);
        jRGarante.setVisible(false);
    }

    public void paraListadosInspector() {
        jPInspector.setVisible(false);
        jLTituloInspector.setVisible(false);
        jLBusquedaInspector.setVisible(false);
        jCBusquedaInspector.setVisible(false);
        jBNuevoInspector.setVisible(false);
        jBModificarInspector.setVisible(false);
        jBEliminarInspector.setVisible(false);
        jBSalirInspector.setVisible(false);
        jLIDInspector.setVisible(false);
        jTIDInspector.setVisible(false);
        jLMatriculaInspector.setVisible(false);
        jTMatriculaInspector.setVisible(false);
        jLNombreInspector.setVisible(false);
        jTNombreInspector.setVisible(false);
        jLApellidoInspector.setVisible(false);
        jTApellidoInspector.setVisible(false);
        jLTelefonoInspector.setVisible(false);
        jTTelefonoInspector.setVisible(false);
        jLActivoInspector.setVisible(false);
        jRInspector.setVisible(false);
    }

    public void paraListadosInquilinosTrue() {
        jTabbedPane1.setVisible(true);
        jPBarraNavegador3.setVisible(true);
        jPInquilinos.setVisible(true);
        jLTituloInquilinos.setVisible(true);
        jLBusquedaInquilinos.setVisible(true);
        jCBusquedaInquilinos.setVisible(true);
        jLIdInquilinos.setVisible(true);
        jTIDInquilino.setVisible(true);
        jBNuevoInquilinos.setVisible(true);
        jBModificarInquilinos.setVisible(true);
        jBEliminarInquilinos.setVisible(true);
        jBSalirInquilinos.setVisible(true);
        jTNombreInquilinos.setVisible(true);
        jLNombreInquilinos.setVisible(true);
        jLApellidoInquilinos.setVisible(true);
        jTApellidoInquilinos.setVisible(true);
        jLDNIInquilinos.setVisible(true);
        jTDNIInquilinos.setVisible(true);
        jLCuitInquilinos.setVisible(true);
        jTLugarTrabajoInquilinos.setVisible(true);
        jLLugarTrabajoInquilinos.setVisible(true);
        jTCuitInquilinos.setVisible(true);
        jLActivoInquilinos.setVisible(true);
        jRInquilino.setVisible(true);

    }

    public void paraListadosGaranteTrue() {
        jPGarante.setVisible(true);
        jLTituloGarante.setVisible(true);
        jLBusquedaGarante.setVisible(true);
        jCBusquedaGarante.setVisible(true);
        jBNuevoGarante.setVisible(true);
        jBModificarGarante.setVisible(true);
        jBEliminarGarante.setVisible(true);
        jBSalirGarante.setVisible(true);
        jLIDGarante.setVisible(true);
        jTIDGarante.setVisible(true);
        jLNombreGarante.setVisible(true);
        jTNombreGarante.setVisible(true);
        jLApellidoGarante.setVisible(true);
        jTApellidoGarante.setVisible(true);
        jLDNIGarante.setVisible(true);
        jTDNIGarante.setVisible(true);
        jLDomicilio.setVisible(true);
        jTDomicilioGarante.setVisible(true);
        jLTelefonoGarante.setVisible(true);
        jLActivoGarante.setVisible(true);
        jRGarante.setVisible(true);

    }

    public void paraListadosInspectorTrue() {
        jPInspector.setVisible(true);
        jLTituloInspector.setVisible(true);
        jLBusquedaInspector.setVisible(true);
        jCBusquedaInspector.setVisible(true);
        jBNuevoInspector.setVisible(true);
        jBModificarInspector.setVisible(true);
        jBEliminarInspector.setVisible(true);
        jBSalirInspector.setVisible(true);
        jLIDInspector.setVisible(true);
        jTIDInspector.setVisible(true);
        jLMatriculaInspector.setVisible(true);
        jTMatriculaInspector.setVisible(true);
        jLNombreInspector.setVisible(true);
        jTNombreInspector.setVisible(true);
        jLApellidoInspector.setVisible(true);
        jTApellidoInspector.setVisible(true);
        jLTelefonoInspector.setVisible(true);
        jTTelefonoInspector.setVisible(true);
        jLActivoInspector.setVisible(true);
        jRInspector.setVisible(true);
    }

    public void cargarCombos() {
        jCBusquedaInquilinos.removeAllItems();
        InquilinoData inquilinoD = new InquilinoData();
        ArrayList<Inquilino> inquilinos = new ArrayList<>();

        for (Inquilino inquilino : inquilinoD.listarInquilinos()) {
            inquilinos.add(inquilino);
            jCBusquedaInquilinos.addItem(inquilino);
        }
        jCBusquedaInquilinos.setRenderer(new DefaultListCellRenderer() {
            @Override
            public Component getListCellRendererComponent(JList<?> list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
                super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);

                if (value instanceof Inquilino) {
                    Inquilino inquilino = (Inquilino) value;

                    if (inquilino.isActivo() == false) {
                        setForeground(Color.RED); // Cambia el color del texto a rojo si el estado es 0
                    } else {
                        setForeground(Color.BLACK); // Restablece el color del texto a negro
                    }
                }

                return this;
            }
        });

        jCBusquedaGarante.removeAllItems();
        GaranteData garanteD = new GaranteData();
        ArrayList<Garante> garantes = new ArrayList<>();

        for (Garante garante : garanteD.listarGarante()) {
            garantes.add(garante);
            jCBusquedaGarante.addItem(garante);

        }
        jCBusquedaGarante.setRenderer(new DefaultListCellRenderer() {
            @Override
            public Component getListCellRendererComponent(JList<?> list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
                super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);

                if (value instanceof Garante) {
                    Garante garante = (Garante) value;

                    if (garante.isActivo() == false) {
                        setForeground(Color.RED); // Cambia el color del texto a rojo si el estado es 0
                    } else {
                        setForeground(Color.BLACK); // Restablece el color del texto a negro
                    }
                }

                return this;
            }
        });

        jCBusquedaInspector.removeAllItems();
        InspectorData inspectorD = new InspectorData();
        ArrayList<Inspector> inspectores = new ArrayList<>();

        for (Inspector inspector : inspectorD.listarInspectores()) {
            inspectores.add(inspector);
            jCBusquedaInspector.addItem(inspector);

        }

        jCBusquedaInspector.setRenderer(new DefaultListCellRenderer() {
            @Override
            public Component getListCellRendererComponent(JList<?> list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
                super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);

                if (value instanceof Inspector) {
                    Inspector inspector = (Inspector) value;

                    if (inspector.isActivo() == false) {
                        setForeground(Color.RED); // Cambia el color del texto a rojo si el estado es 0
                    } else {
                        setForeground(Color.BLACK); // Restablece el color del texto a negro
                    }
                }

                return this;
            }
        });

    }

    public void rellenarCampos() {

        // relleno campos pestaña inquilinos
        Inquilino inquilinoSelecionado = (Inquilino) jCBusquedaInquilinos.getSelectedItem();
        // boolean activo = jrbEstado.isSelected();

        if (inquilinoSelecionado != null) {
            jTIDInquilino.setText(String.valueOf(inquilinoSelecionado.getIdInquilino()));
            jTNombreInquilinos.setText(inquilinoSelecionado.getNombre());
            jTApellidoInquilinos.setText(inquilinoSelecionado.getApellido());
            jTDNIInquilinos.setText(String.valueOf(inquilinoSelecionado.getDni()));
            jTCuitInquilinos.setText(String.valueOf(inquilinoSelecionado.getCuit()));
            jTLugarTrabajoInquilinos.setText(inquilinoSelecionado.getLugarTrabajo());
            jRInquilino.setSelected(inquilinoSelecionado.isActivo());

            //habilito botones luego de ejecutar acccion!
            //Habilito botones si esta todo OK!
//                if (ae.isActivo() == true) {
//                    habilitarBusquedaBotones();
//                } else {
//                    desHabilitarBotones();
//                    jbModificar.setEnabled(true);
//
//                }
        }

        // relleno campos pestaña garantes
        Garante garanteSelecionado = (Garante) jCBusquedaGarante.getSelectedItem();
//            boolean activo = jrbEstado.isSelected();

        if (garanteSelecionado != null) {
            jTIDGarante.setText(String.valueOf(garanteSelecionado.getIdGarante()));
            jTNombreGarante.setText(garanteSelecionado.getNombre());
            jTApellidoGarante.setText(garanteSelecionado.getApellido());
            jTDNIGarante.setText(String.valueOf(garanteSelecionado.getDni()));
            jTDomicilioGarante.setText(garanteSelecionado.getDomicilio());
            jTTelefonoGarante.setText(String.valueOf(garanteSelecionado.getTelefono()));
            jRGarante.setSelected(garanteSelecionado.isActivo());

            //habilito botones luego de ejecutar acccion!
            //Habilito botones si esta todo OK!
//                if (ae.isActivo() == true) {
//                    habilitarBusquedaBotones();
//                } else {
//                    desHabilitarBotones();
//                    jbModificar.setEnabled(true);
//
//                }
        }
        //relleno campos pestaña inspectores:

        Inspector inspectorSelecionado = (Inspector) jCBusquedaInspector.getSelectedItem();
        //boolean activo = jrbEstado.isSelected();

        if (inspectorSelecionado != null) {
            jTIDInspector.setText(String.valueOf(inspectorSelecionado.getIdInspector()));
            jTMatriculaInspector.setText(inspectorSelecionado.getMatricula());
            jTNombreInspector.setText(inspectorSelecionado.getNombre());
            jTApellidoInspector.setText(inspectorSelecionado.getApellido());
            jTTelefonoInspector.setText(String.valueOf(inspectorSelecionado.getTelefono()));
            jRInspector.setSelected(inspectorSelecionado.isActivo());

            //habilito botones luego de ejecutar acccion!
            //Habilito botones si esta todo OK!
//                if (ae.isActivo() == true) {
//                    habilitarBusquedaBotones();
//                } else {
//                    desHabilitarBotones();
//                    jbModificar.setEnabled(true);
//
//                }
        }
    }

    public void borrarCampos() {
        jTIDInquilino.setText("");
        jTNombreInquilinos.setText("");
        jTApellidoInquilinos.setText("");
        jTDNIInquilinos.setText("");
        jTCuitInquilinos.setText("");
        jTLugarTrabajoInquilinos.setText("");
        jRInquilino.setSelected(false);

        jTIDInspector.setText("");
        jTMatriculaInspector.setText("");
        jTNombreInspector.setText("");
        jTApellidoInspector.setText("");
        jTTelefonoInspector.setText("");
        jRInspector.setSelected(false);

        jTIDGarante.setText("");
        jTNombreGarante.setText("");
        jTApellidoGarante.setText("");
        jTDNIGarante.setText("");
        jTDomicilioGarante.setText("");
        jTTelefonoGarante.setText("");
        jRGarante.setSelected(false);
    }
}