/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package igu;

import entidades.Propiedad;
import java.awt.Dimension;
import javax.swing.JComponent;

/**
 *
 * @author Pirrupi
 */
public class MenuPropiedades extends javax.swing.JInternalFrame {

    /**
     * Creates new form MenuPropiedades
     */
    public MenuPropiedades() {
        initComponents(); 
        QuitarLaBarraTitulo();

    }
    //defino dos métodosdentro del JInternalFrame y lo instanciamos de la siguiente manera.
    private JComponent Barra = ((javax.swing.plaf.basic.BasicInternalFrameUI) getUI()).getNorthPane();
    private Dimension DimensionBarra = null;
    //A continuación creamos una función dentro del mismo JInternalFrame como el ejemplo siguiente:

    public void QuitarLaBarraTitulo() {
        Barra = ((javax.swing.plaf.basic.BasicInternalFrameUI) getUI()).getNorthPane();
        DimensionBarra = Barra.getPreferredSize();
        Barra.setSize(0, 0);
        Barra.setPreferredSize(new Dimension(0, 0));
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPPropiedades = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jCBusquedaPropiedades = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jTIDPropietarios = new javax.swing.JTextField();
        jTDireccion = new javax.swing.JTextField();
        jTAltura = new javax.swing.JTextField();
        jTTipo = new javax.swing.JTextField();
        jTSuperTotal = new javax.swing.JTextField();
        jTPrecioTasado = new javax.swing.JTextField();
        jTAntiguedad = new javax.swing.JTextField();
        jTServicios = new javax.swing.JTextField();
        jTInspector = new javax.swing.JTextField();
        jTZona = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jTEstado = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jTDisponibilidad = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTObservaciones = new javax.swing.JTextArea();
        jBNuevo = new javax.swing.JButton();
        jBModificar = new javax.swing.JButton();
        jBEliminar = new javax.swing.JButton();
        jBSalir = new javax.swing.JButton();
        jPBarraNavegador = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPLogin = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);

        jPPropiedades.setBackground(new java.awt.Color(55, 55, 54));
        jPPropiedades.setMinimumSize(new java.awt.Dimension(748, 635));
        jPPropiedades.setPreferredSize(new java.awt.Dimension(748, 635));
        jPPropiedades.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 204, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Busqueda");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPPropiedades.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 161, 131, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 204, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/casita.png"))); // NOI18N
        jLabel2.setText("  Formulario Propiedades");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPPropiedades.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 290, -1));

        jCBusquedaPropiedades.setBackground(new java.awt.Color(153, 153, 153));
        jCBusquedaPropiedades.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        jPPropiedades.add(jCBusquedaPropiedades, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 165, 218, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 204, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("ID Propietarios");
        jLabel10.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPPropiedades.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 217, 131, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 204, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("Direccion");
        jLabel11.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPPropiedades.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 247, 131, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 204, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText("Altura");
        jLabel12.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPPropiedades.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 277, 131, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 204, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setText("Tipo");
        jLabel13.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPPropiedades.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 307, 131, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 204, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel14.setText("Super. Total");
        jLabel14.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPPropiedades.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 337, 131, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 204, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel15.setText("Precio Tasado");
        jLabel15.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPPropiedades.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 371, 131, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(51, 204, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel18.setText("Antiguedad");
        jLabel18.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPPropiedades.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 397, 131, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 204, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel19.setText("Servicios");
        jLabel19.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPPropiedades.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 427, 131, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(51, 204, 255));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel20.setText("Inspector");
        jLabel20.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPPropiedades.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 455, 131, -1));

        jLabel21.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(51, 204, 255));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel21.setText("Zona");
        jLabel21.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPPropiedades.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 486, 131, -1));

        jTIDPropietarios.setBackground(new java.awt.Color(153, 153, 153));
        jTIDPropietarios.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        jTIDPropietarios.setForeground(new java.awt.Color(51, 51, 51));
        jPPropiedades.add(jTIDPropietarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 215, 187, -1));

        jTDireccion.setBackground(new java.awt.Color(153, 153, 153));
        jTDireccion.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        jTDireccion.setForeground(new java.awt.Color(51, 51, 51));
        jTDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTDireccionActionPerformed(evt);
            }
        });
        jPPropiedades.add(jTDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 245, 187, -1));

        jTAltura.setBackground(new java.awt.Color(153, 153, 153));
        jTAltura.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        jTAltura.setForeground(new java.awt.Color(51, 51, 51));
        jTAltura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTAlturaActionPerformed(evt);
            }
        });
        jPPropiedades.add(jTAltura, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 275, 187, -1));

        jTTipo.setBackground(new java.awt.Color(153, 153, 153));
        jTTipo.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        jTTipo.setForeground(new java.awt.Color(51, 51, 51));
        jTTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTTipoActionPerformed(evt);
            }
        });
        jPPropiedades.add(jTTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 305, 187, -1));

        jTSuperTotal.setBackground(new java.awt.Color(153, 153, 153));
        jTSuperTotal.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        jTSuperTotal.setForeground(new java.awt.Color(51, 51, 51));
        jTSuperTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTSuperTotalActionPerformed(evt);
            }
        });
        jPPropiedades.add(jTSuperTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 335, 187, -1));

        jTPrecioTasado.setBackground(new java.awt.Color(153, 153, 153));
        jTPrecioTasado.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        jTPrecioTasado.setForeground(new java.awt.Color(51, 51, 51));
        jTPrecioTasado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTPrecioTasadoActionPerformed(evt);
            }
        });
        jPPropiedades.add(jTPrecioTasado, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 365, 187, -1));

        jTAntiguedad.setBackground(new java.awt.Color(153, 153, 153));
        jTAntiguedad.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        jTAntiguedad.setForeground(new java.awt.Color(51, 51, 51));
        jTAntiguedad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTAntiguedadActionPerformed(evt);
            }
        });
        jPPropiedades.add(jTAntiguedad, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 395, 187, -1));

        jTServicios.setBackground(new java.awt.Color(153, 153, 153));
        jTServicios.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        jTServicios.setForeground(new java.awt.Color(51, 51, 51));
        jTServicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTServiciosActionPerformed(evt);
            }
        });
        jPPropiedades.add(jTServicios, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 425, 187, -1));

        jTInspector.setBackground(new java.awt.Color(153, 153, 153));
        jTInspector.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        jTInspector.setForeground(new java.awt.Color(51, 51, 51));
        jTInspector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTInspectorActionPerformed(evt);
            }
        });
        jPPropiedades.add(jTInspector, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 455, 187, -1));

        jTZona.setBackground(new java.awt.Color(153, 153, 153));
        jTZona.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        jTZona.setForeground(new java.awt.Color(51, 51, 51));
        jTZona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTZonaActionPerformed(evt);
            }
        });
        jPPropiedades.add(jTZona, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 485, 187, -1));

        jLabel24.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(51, 204, 255));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel24.setText("Estado");
        jLabel24.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPPropiedades.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, 106, -1));

        jTEstado.setBackground(new java.awt.Color(153, 153, 153));
        jTEstado.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        jTEstado.setForeground(new java.awt.Color(51, 51, 51));
        jTEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTEstadoActionPerformed(evt);
            }
        });
        jPPropiedades.add(jTEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(513, 215, 200, -1));

        jLabel25.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(51, 204, 255));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel25.setText("Disponibilidad");
        jLabel25.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPPropiedades.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(378, 247, 118, -1));

        jTDisponibilidad.setBackground(new java.awt.Color(153, 153, 153));
        jTDisponibilidad.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        jTDisponibilidad.setForeground(new java.awt.Color(51, 51, 51));
        jTDisponibilidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTDisponibilidadActionPerformed(evt);
            }
        });
        jPPropiedades.add(jTDisponibilidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(512, 245, 200, -1));

        jLabel26.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(51, 204, 255));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel26.setText("Activo");
        jLabel26.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPPropiedades.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(378, 275, 118, -1));

        jLabel22.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Activo");
        jPPropiedades.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(519, 280, 90, -1));

        jLabel27.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(51, 204, 255));
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel27.setText("Observaciones");
        jLabel27.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPPropiedades.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 320, 118, -1));

        jTObservaciones.setBackground(new java.awt.Color(153, 153, 153));
        jTObservaciones.setColumns(20);
        jTObservaciones.setRows(5);
        jScrollPane1.setViewportView(jTObservaciones);

        jPPropiedades.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 352, 312, 157));

        jBNuevo.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        jBNuevo.setForeground(new java.awt.Color(51, 204, 255));
        jBNuevo.setText("Nuevo");
        jBNuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPPropiedades.add(jBNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 546, -1, -1));

        jBModificar.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        jBModificar.setForeground(new java.awt.Color(51, 204, 255));
        jBModificar.setText("Modificar");
        jBModificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPPropiedades.add(jBModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 546, -1, -1));

        jBEliminar.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        jBEliminar.setForeground(new java.awt.Color(51, 204, 255));
        jBEliminar.setText("Eliminar");
        jBEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPPropiedades.add(jBEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(416, 546, -1, -1));

        jBSalir.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        jBSalir.setForeground(new java.awt.Color(51, 204, 255));
        jBSalir.setText("Salir");
        jBSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalirActionPerformed(evt);
            }
        });
        jPPropiedades.add(jBSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(536, 546, -1, -1));

        jPBarraNavegador.setBackground(new java.awt.Color(153, 153, 153));

        jLabel9.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("Inicio > Propiedades");
        jLabel9.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout jPBarraNavegadorLayout = new javax.swing.GroupLayout(jPBarraNavegador);
        jPBarraNavegador.setLayout(jPBarraNavegadorLayout);
        jPBarraNavegadorLayout.setHorizontalGroup(
            jPBarraNavegadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPBarraNavegadorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPBarraNavegadorLayout.setVerticalGroup(
            jPBarraNavegadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPBarraNavegadorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPPropiedades.add(jPBarraNavegador, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 740, -1));

        jPLogin.setBackground(new java.awt.Color(51, 51, 51));
        jPLogin.setMinimumSize(new java.awt.Dimension(748, 635));

        jLabel3.setText("hola");

        javax.swing.GroupLayout jPLoginLayout = new javax.swing.GroupLayout(jPLogin);
        jPLogin.setLayout(jPLoginLayout);
        jPLoginLayout.setHorizontalGroup(
            jPLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPLoginLayout.createSequentialGroup()
                .addGap(296, 296, 296)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(355, Short.MAX_VALUE))
        );
        jPLoginLayout.setVerticalGroup(
            jPLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPLoginLayout.createSequentialGroup()
                .addGap(264, 264, 264)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(315, Short.MAX_VALUE))
        );

        jPPropiedades.add(jPLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(-12, -10, 760, 590));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 748, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPPropiedades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 635, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPPropiedades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTDireccionActionPerformed

    private void jTAlturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTAlturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTAlturaActionPerformed

    private void jTTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTTipoActionPerformed

    private void jTSuperTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTSuperTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTSuperTotalActionPerformed

    private void jTPrecioTasadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTPrecioTasadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTPrecioTasadoActionPerformed

    private void jTAntiguedadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTAntiguedadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTAntiguedadActionPerformed

    private void jTServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTServiciosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTServiciosActionPerformed

    private void jTInspectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTInspectorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTInspectorActionPerformed

    private void jTZonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTZonaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTZonaActionPerformed

    private void jTEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTEstadoActionPerformed

    private void jTDisponibilidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTDisponibilidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTDisponibilidadActionPerformed

    private void jBSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBSalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBEliminar;
    private javax.swing.JButton jBModificar;
    private javax.swing.JButton jBNuevo;
    private javax.swing.JButton jBSalir;
    private javax.swing.JComboBox<Propiedad> jCBusquedaPropiedades;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPBarraNavegador;
    private javax.swing.JPanel jPLogin;
    private javax.swing.JPanel jPPropiedades;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTAltura;
    private javax.swing.JTextField jTAntiguedad;
    private javax.swing.JTextField jTDireccion;
    private javax.swing.JTextField jTDisponibilidad;
    private javax.swing.JTextField jTEstado;
    private javax.swing.JTextField jTIDPropietarios;
    private javax.swing.JTextField jTInspector;
    private javax.swing.JTextArea jTObservaciones;
    private javax.swing.JTextField jTPrecioTasado;
    private javax.swing.JTextField jTServicios;
    private javax.swing.JTextField jTSuperTotal;
    private javax.swing.JTextField jTTipo;
    private javax.swing.JTextField jTZona;
    // End of variables declaration//GEN-END:variables
}
